apiVersion: v1
kind: Pod
metadata:
    name: pod-users
    labels:
        app: cloudgames-users
spec:
    containers:
        - name: fiapcloudgames-users
          image:  <url da imagem Dockerfile no ACR>
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80 # Porta que a aplicação .NET está ouvindo
          env:
            - name: Jwt__Key
              valueFrom:
                configMapKeyRef:
                    name: secret-users
                    key: Jwt__Key
            
            - name: Jwt__Issuer
              valueFrom:
                configMapKeyRef:
                    name: secret-users
                    key: Jwt__Issuer
                   