apiVersion: v1
kind: Secret
metadata:
    name: secret-users
type: Opaque
stringData:
    Jwt__Key: "12345678901234567890123456789012" # Idealmente usar informações a serem utilizadas em dev e fazer um replace em produção
    Jwt__Issuer: "FIAPCloudGames" # Idealmente usar informações a serem utilizadas em dev e fazer um replace em produção
    