apiVersion: v1
kind: Service
metadata:
    name: svc-users
spec:
    type: NodePort
    ports:
        - port: 80 # Porta padrão da service
          targetPort: 8080 # Porta alvo do Pod
    selector:
        app: cloudgames-users