apiVersion: v1
kind: Service
metadata:
    name: svc-users
spec:
    type: NodePort
    ports:
        - port: 80 # Porta padrão da service
          targetPort: 80 # Porta alvo do Pod, que, nesse caso, também é 80
    selector:
        app: cloudgames-users